version: 2
updates:
- package-ecosystem: pip
  insecure-external-code-execution: allow
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "20:00"
    timezone: America/Chicago
  open-pull-requests-limit: 3
  reviewers:
  - kennytrytek
